onlineschool/accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

onlineschool/onlineschool/urls.py
from django.contrib import admin
from django.urls import path, include
from school_app.views import IndexView,LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('school/', include('school_app.urls', namespace='school_app'))

]

onlineschool/school_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name ='school_app'

urlpatterns=[
    #path('', views.index, name='index'),
    path('', views.SchoolListView.as_view(), name='list' ),
    path('<pk>', views.SchoolDetailView.as_view(), name='details')
]

onlineschool/accounts/models.py
from django.db import models

# Create your models here.

onlineschool/school_app/models.py
from django.db import models

# Create your models here.

class School (models.Model):
    name = models.CharField(max_length=264)
    principal = models.CharField(max_length=264)
    location = models.CharField(max_length=264)

    def __str__(self):
       return self.name

class Student(models.Model):
    name = models.CharField(max_length=264)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

onlineschool/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

from django.urls import reverse_lazy

from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

onlineschool/school_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, ListView, DetailView
from .models import School, Student

from . import models

class LoginView(TemplateView):
    template_name = 'school_app/login.html'

class IndexView(TemplateView):
    template_name = 'school_app/index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'school_app/school_detail.html'
    

onlineschool/school_app/templates/school_app/school_app_base.html
<!DOCTYPE html>
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <title>School Management System</title>
</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <button type="button" class="navbar-toggler"  data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar toggler-icon"></span>
            </button>
            <div class="navbar-header">
                <a class="navbar-brand" href="">School Managament</a>
            </div>
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{%url 'school_app:list'%}">Schools</a></li>
                   <!-- <li><a class="nav-link" href="{%url 'admin:index'%}">Admin</a></li>-->
                    <li><a class="nav-link" href="">Students</a></li>
                    <li><a class="nav-link" href="{%url 'logout'%}">Log out</a></li>
                    <li>Welcome {{ user.username }}!</li>

                {% else %}
                    <li><a class="nav-link" href="">Contact</a></li>
                    <li><a class="nav-link" href="">About US</a>
                    <li><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
                {% endif %}
            </ul>
            <!--<ul class="nav navbar-right">
                <li><a class="nav-link" href="{%url 'login'%}">Login</a></li>

            </ul>-->

        </div>
   </nav>
    <div class="container">
        {%block body%}

        {%endblock%}

    </div>
</body>
<script src="{%static 'js/bootstrap.js'%}"></script>
<script src="{%static 'js/jquery-3.5.1.min.js'%}"></script>
</html>

onlineschool/school_app/templates/school_app/school_detail.html
<!DOCTYPE html>
{%extends "school_app/school_app_base.html"%}

{%block body%}
<div class="jumbotron">
        <h2>School Details:</h2>
        <p>Name: {{ school_detail.name}}</p>
        <p>Principal : {{ school_detail.principal}}</p>
        <p>Location : {{school_detail.location}}</p>
    <h3>Students :</h3>

        <ol>
            {% for student in school_detail.students.all%}
            <li><p>{{student.name}}</p></li>
            {%endfor%}
        </ol>

</div>


{%endblock%}

onlineschool/school_app/templates/school_app/school_list.html
<!DOCTYPE html>
{%extends "school_app/school_app_base.html"%}

{%block body%}
<div class="jumbotron">
    <h1>School List</h1>

    <ol>
         {% for school in schools%}
         <h2>
             <li><a href="{{school.id}}">{{school.name}}</a></li>
        </h2>
        {%endfor%}
    </ol>

</div>
{%endblock%}

onlineschool/templates/school_app/base.html
<!DOCTYPE html>
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <title>Online School Management System</title>
</head>
<body>

    <!--Nav bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">School Managament</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{%url 'school_app:list'%}">Schools <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'logout'%}">Log out</a>
                </li>
                <li>Welcome : {{ user.username }}!</li>

                {% else %}
                <li><a class="nav-link" href="">Contact</a></li>
                <li><a class="nav-link" href="">About US</a>
                <li><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
                {% endif %}
              </ul>
            </div>
          </nav>
    <!--end navbar-->
    <div class="container">
        {%block body%}

        {%endblock%}

    </div>
</body>
<script src="{%static 'js/jquery.min.js'%}"></script>
<script src="{%static 'js/bootstrap.min.js'%}"></script>

</html>

onlineschool/templates/school_app/index.html
<!DOCTYPE html>
{%extends "school_app/base.html"%}


{%block body%}
    <div class="jumbotron">
            <h1>List of Schools</h1>
    </div>

{%endblock%}

onlineschool/templates/school_app/login.html
<!DOCTYPE html>
{%extends "school_app/base.html"%}
{%block body%}
<form action="">
    <label for="">Username:</label>
    <input type="text" >
    <label for="">Password :</label>
    <input type="password">
    <input class="btn btn-primary" type="button" value="Submit">
</form>
{%endblock%}

onlineschool/templates/school_app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

onlineschool/templates/shared/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
    </div>
  </nav>